### ISSUE TITLE
Add option to transform front matter

### ISSUE THREAD

**Issue by Pandapip1** [Stuyk/vitepress-plugin-simple-search#14]
I have a `transformPageData` config entry in my vitepress website, and it's used to add a prefix to all the titles of the files in a specific folder. However, this plugin appears to not be detecting those updates. Is it possible to add a config for transforming the front matter?

**Comment by Stuyk** [comment]
@Pandapip1 I adjusted your typings for the transformer. They were incorrect and `1.3.4` should have them available.
