### ISSUE TITLE
Search includes content from node_modules

### ISSUE THREAD

**Issue by nie7321** [Stuyk/vitepress-plugin-simple-search#5]
I've got a vitepress site in the root of my project, as opposed to in the `docs/` folder.

It seems that the search is including markdown files from `node_modules/` when it builds its index. That is undesirable.

**Comment by Stuyk** [comment]
Will look into ignoring node_modules folder and adding a directory you can specify to look for files.

**Comment by Stuyk** [comment]
Open a new issue if version `1.3.0` is not sufficient.
