### ISSUE TITLE
The vitepress-plugin-simple-search folder is empty after "npm install"

### ISSUE THREAD

**Issue by ilearnio** [Stuyk/vitepress-plugin-simple-search#9]
Hey. It doesn't work completely because there are no files besides package.json and README.md.

![image](https://user-images.githubusercontent.com/14331216/205510731-eeb9c6dd-993b-436f-94f2-651b6ccac269.png)

**Comment by jeffholst** [comment]
I confirmed the same.  In version 1.3.1 I'm no longer seeing the /dist folder in the NPM.

**Comment by Stuyk** [comment]
@ilearnio @jeffholst 

Just published version `1.3.2` and added a prepublish script to the package.json to make sure the `dist` gets generated for distributions. Apologies for that. Should be good to go now.

Lemme know if it all looks good now.

**Comment by jeffholst** [comment]
@Stuyk - The `dist` folder is in the NPM, but now I'm getting the error reported in #6 ( _.existsSync is not a function)

@froko - do you mind sharing your fix as a PR?

**Comment by froko** [comment]
@jeffholst I've just created a PR which closes #6

**Comment by Stuyk** [comment]
@froko Merged and incremented to `1.3.3`

**Comment by jeffholst** [comment]
> @jeffholst I've just created a PR which closes #6

Thx @froko.

@Stuyk - everything is working for me now.
